-- Criar tabela de unidades de embalagem
CREATE TABLE public.packaging_units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES public.tenants(id),
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  UNIQUE(tenant_id, code)
);

-- Habilitar RLS
ALTER TABLE public.packaging_units ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Users can view tenant packaging_units"
ON public.packaging_units FOR SELECT
USING (tenant_id = get_user_tenant_id(auth.uid()));

CREATE POLICY "Users can insert tenant packaging_units"
ON public.packaging_units FOR INSERT
WITH CHECK (tenant_id = get_user_tenant_id(auth.uid()));

CREATE POLICY "Users can update tenant packaging_units"
ON public.packaging_units FOR UPDATE
USING (tenant_id = get_user_tenant_id(auth.uid()));

CREATE POLICY "Users can delete tenant packaging_units"
ON public.packaging_units FOR DELETE
USING (tenant_id = get_user_tenant_id(auth.uid()));