create table public.notifications (
  id bigint generated by default as identity not null,
  user_id uuid references auth.users not null,
  tenant_id bigint references public.tenants,
  title text not null,
  message text not null,
  link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint notifications_pkey primary key (id)
);

alter table public.notifications enable row level security;

create policy "Users can view their own notifications"
on public.notifications for select
using (auth.uid() = user_id);

create policy "Users can update their own notifications"
on public.notifications for update
using (auth.uid() = user_id);
