-- Ensure quote_snapshots table exists (idempotent)
CREATE TABLE IF NOT EXISTS public.quote_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id bigint REFERENCES public.quotes(id) ON DELETE CASCADE,
    snapshot_data jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    created_by uuid REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.quote_snapshots ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Authenticated users can insert snapshots" ON public.quote_snapshots;
DROP POLICY IF EXISTS "Users can view snapshots for their tenant" ON public.quote_snapshots;

-- Policy: Allow authenticated users to insert snapshots
-- Validates that the user is authenticated.
CREATE POLICY "Authenticated users can insert snapshots"
ON public.quote_snapshots
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Allow users to select snapshots associated with quotes from their tenant
-- This requires joining with the quotes table to check tenant_id
CREATE POLICY "Users can view snapshots for their tenant"
ON public.quote_snapshots
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.quotes q
        WHERE q.id = quote_snapshots.quote_id
        AND q.tenant_id = public.get_user_tenant_id(auth.uid())
    )
);

-- Grant permissions (just in case)
GRANT ALL ON TABLE public.quote_snapshots TO authenticated;
GRANT ALL ON TABLE public.quote_snapshots TO service_role;
